version: 2.0

jobs:
  noop:
    docker:
      - image: circleci/node:10.16.3 # the primary container, where your job's commands are run
    steps:
      - run: echo "Noop Do nothing."

  setup:
    docker:
      - image: circleci/node:10.16.3 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install
      - run: cp yarn.lock yarn.lock.tmp
      - run: yarn add cypress
      - run: rm yarn.lock
      - run: mv yarn.lock.tmp yarn.lock

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      # build
      - run:
          name: Build site
          command: yarn build

      - run:
          name: Build docs
          command: yarn build:docs

      - persist_to_workspace:
          root: ./
          paths:
            - styleguide

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - attach_workspace:
          at: ./

      - run:
          name: Deploy Docs to Netlify
          command: yarn deploy:docs --message "Deploy from CircleCI"

  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Unit test
          command: yarn test:ci --runInBand --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'reports/junit'
            JEST_JUNIT_OUTPUT_NAME: 'js-test-results.xml'

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit

  teste2e:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn run test:e2e:ci

workflows:
  version: 2
  install-build-and-test:
    jobs:
      - noop:
          filters:
            branches:
              ignore: master

      - setup
      - test:
          requires:
            - setup
      - teste2e:
          requires:
            - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
